import laravel from 'laravel-vite-plugin';
import { defineConfig } from 'vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/app-assets/css/bootstrap.css',
                'resources/css/app-assets/css/bootstrap-extended.css',
                'resources/css/app-assets/css/colors.css',
                'resources/css/app-assets/css/components.css',
                'resources/css/app-assets/css/core/menu/menu-types/vertical-menu.css',
                'resources/css/app-assets/css/pages/dashboard-analytics.css',
                'resources/css/app-assets/css/pages/authentication.css',
                'resources/css/app-assets/css/plugins/forms/validation/form-validation.css',
                'resources/css/app-assets/css/plugins/extensions/toastr.css',
                'resources/css/app-assets/vendors/css/vendors.min.css',
                'resources/css/app-assets/vendors/css/charts/apexcharts.css',
                'resources/css/app-assets/vendors/css/animate/animate.css',
                'resources/css/app-assets/vendors/css/extensions/dragula.min.css',
                'resources/css/app-assets/vendors/css/forms/select/select2.min.css',
                'resources/css/app-assets/vendors/css/extensions/toastr.css',
                'resources/css/app-assets/vendors/css/tables/datatable/datatables.min.css',
                'resources/js/app.js',
                'resources/js/js/core/app-menu.js',
                'resources/js/js/core/app.js',
                'resources/js/js/scripts/components.js',
                'resources/js/js/scripts/footer.js',
                'resources/js/js/scripts/forms/validation/form-validation.js',
                'resources/js/js/scripts/forms/select/form-select2.js',
                'resources/js/js/scripts/extensions/toastr.js',
                'resources/css/app-assets/vendors/js/vendors.min.js',
                'resources/css/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.js',
                'resources/css/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.js',
                'resources/css/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js',
                'resources/css/app-assets/vendors/js/extensions/numeral/numeral.js',
                'resources/css/app-assets/vendors/js/extensions/dragula.min.js',
                'resources/css/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js',
                'resources/css/app-assets/vendors/js/forms/select/select2.full.min.js',
                'resources/css/app-assets/vendors/js/extensions/toastr.min.js',
                'resources/css/app-assets/vendors/js/ui/unison.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/datatables.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/buttons.html5.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/buttons.print.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/pdfmake.min.js',
                'resources/css/app-assets/vendors/js/tables/datatable/vfs_fonts.js',
            ],
            refresh: true,
        }),
    ],
});
