name: Deploy Laravel to Azure App Service

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo, pdo_sqlsrv, sqlsrv, mbstring, xml, bcmath

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Generate application key
      run: php artisan key:generate --show

    - name: Create deployment artifact
      run: |
        mkdir -p deployment
        tar -czf deployment/app.tar.gz \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='tests' \
          --exclude='.env*' \
          --exclude='storage/logs/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          .

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gestor-tareas-app'  # Cambia por tu nombre de App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment/app.tar.gz

    - name: Run database migrations
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az webapp ssh --name gestor-tareas-app --resource-group gestor-tareas-rg --command "cd /home/site/wwwroot && php artisan migrate --force"
          az webapp ssh --name gestor-tareas-app --resource-group gestor-tareas-rg --command "cd /home/site/wwwroot && php artisan db:seed --force"
